### PR TITLE
all packages

### PR DESCRIPTION
**Pull request by IanButterworth**

### CODE REVIEW

**Comment by IanButterworth** [comment]
Just saw that:
`Your platform aarch64-linux-musl is not supported by this package!`
`Your platform armv7l-linux-musl is not supported by this package!`

**Comment by SimonDanisch** [comment]
Where did it say that? That sounds like you would need to upgrade https://github.com/staticfloat/OggBuilder/ first!
I guess that's what you're trying: https://github.com/staticfloat/OggBuilder/pull/2
Why did you close?

**Comment by IanButterworth** [comment]
Oh, right... didn’t think that through

**Comment by IanButterworth** [comment]
I somehow didn't realize that the musl licenses had been added in ogg release [v1.3.3-7](https://github.com/staticfloat/OggBuilder/releases/tag/v1.3.3-7) already

**Pull request merged**
